# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieLibrary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieLibrary
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'AlamofireImage', '~> 4.1'

  target 'MovieLibraryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieLibraryUITests' do
    # Pods for testing
  end

end
